CREATE TABLE IF NOT EXISTS scores (
  test_id TEXT NOT NULL,
  first_name_norm TEXT NOT NULL,
  last_name_norm TEXT NOT NULL,
  email TEXT NOT NULL,
  test_name TEXT NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  correct INTEGER NOT NULL,
  total INTEGER NOT NULL,
  percent INTEGER NOT NULL,
  passed TEXT NOT NULL,
  answers TEXT NOT NULL,
  correct_answers TEXT NOT NULL,
  client_timestamp TEXT,
  attempt_started_at TEXT,
  completed_at TEXT,
  duration_seconds INTEGER,
  source_url TEXT,
  user_agent TEXT,
  evaluation_submitted_at TEXT,
  training_relevance INTEGER,
  conceptual_clarity INTEGER,
  practical_applicability INTEGER,
  governance_confidence INTEGER,
  codex_workflow_confidence INTEGER,
  materials_quality INTEGER,
  pace_and_depth INTEGER,
  overall_satisfaction INTEGER,
  recommend_training TEXT,
  most_valuable_takeaway TEXT,
  improvement_suggestion TEXT,
  suggested_ai_automation_use_cases TEXT,
  raw_json TEXT NOT NULL,
  submission_count INTEGER NOT NULL DEFAULT 1,
  received_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (test_id, first_name_norm, last_name_norm, email)
);

CREATE INDEX IF NOT EXISTS idx_scores_email ON scores(email);
CREATE INDEX IF NOT EXISTS idx_scores_test_updated ON scores(test_id, updated_at);
